export const SET_INIT_FORM_STATE = "SET_INIT_FORM_STATE";
export const SET_COMMON_FIELD = "SET_COMMON_FIELD";
export const ADD_CHECKBOX_VALUE = "ADD_CHECKBOX_VALUE";
export const REMOVE_CHECKBOX_VALUE = "REMOVE_CHECKBOX_VALUE";
export const RESET_FORM = "RESET_FORM";

export const FETCH_MARRIAGE_FORM = {
  START: "FETCH_MARRIAGE_FORM_START",
  SUCCESS: "FETCH_MARRIAGE_FORM_SUCCESS",
  FAILURE: "FETCH_MARRIAGE_FORM_FAILURE",
};
